#-------------------------------------------------------------------------------
#                                 Data Cleaning 
#-------------------------------------------------------------------------------

gc() # Clear cache
rm(list = ls()) # Remove objects

path = "/Users/bianca/Desktop/X/Policy in Action/Data/Raw/CSV"

library(dplyr)

# Open dataset
enquete_2023 = read.csv2(file = paste0(path, "/2023 Enquête Urgences Structure (CSV).csv"),
                         fileEncoding = "latin1") # Decode accented characters

# Get a sense of the dataset
View(enquete_2023) # View dataset
summary(enquete_2023) # Describe columns 
sum(is.na(enquete_2023)) # Number of missing values

# Change column names
enquete_2023 = enquete_2023 %>%
  rename(
    id_pa = ID_POINT_D_ACCUEIL, 
    finess0 = FINESS,
    structure = TYPE_PA,
    nom_etab = STR_A1,
    finess = STR_A2,
    nom_structure = STR_A3,
    h8_pat_noUHCD_att = STR_A6,
    h18_pat_noUHCD_att = STR_B6,
    h22_pat_noUHCD_att = STR_C6,
    h8j1_pat_noUHCD_att = STR_D6,
    h8_pat_UHCD_noatt = STR_A7,
    h18_pat_UHCD_noatt = STR_B7,
    h22_pat_UHCD_noatt = STR_C7,
    h8j1_pat_UHCD_noatt = STR_D7,
    h8_pat_UHCD_att = STR_A8,
    h18_pat_UHCD_att = STR_B8,
    h22_pat_UHCD_att = STR_C8,
    h8j1_pat_UHCD_att = STR_D8,
    h8_autpat_noUHCD_att = STR_A9,
    h18_autpat_noUHCD_att = STR_B9,
    h22_autpat_noUHCD_att = STR_C9,
    h8j1_autpat_noUHCD_att = STR_D9,
    h8_pat_sort = STR_A10,
    h18_pat_sort = STR_B10,
    h22_pat_sort = STR_C10,
    h8j1_pat_sort = STR_D10,
    h8_med_perm = STR_A11,
    h18_med_perm = STR_B11,
    h22_med_perm = STR_C11,
    h8j1_med_perm = STR_D11,
    h8_med_jun = STR_A12,
    h18_med_jun = STR_B12,
    h22_med_jun = STR_C12,
    h8j1_med_jun = STR_D12,
    h8_med_interim = STR_A13,
    h18_med_interim = STR_B13,
    h22_med_interim = STR_C13,
    h8j1_med_interim = STR_D13,
    h8_cad = STR_A14,
    h18_cad = STR_B14,
    h22_cad = STR_C14,
    h8j1_cad = STR_D14,
    h8_inf = STR_A15,
    h18_inf = STR_B15,
    h22_inf = STR_C15,
    h8j1_inf = STR_D15,
    h8_aid_soign = STR_A16,
    h18_aid_soign = STR_B16,
    h22_aid_soign = STR_C16,
    h8j1_aid_soign = STR_D16,
    h8_ag_serv = STR_A17,
    h18_ag_serv = STR_B17,
    h22_ag_serv = STR_C17,
    h8j1_ag_serv = STR_D17,
    h8_secr = STR_A18,
    h18_secr = STR_B18,
    h22_secr = STR_C18,
    h8j1_secr = STR_D18,
    h8_branc = STR_A19,
    h18_branc = STR_B19,
    h22_branc = STR_C19,
    h8j1_branc = STR_D19,
    h8_autpers = STR_A20,
    h18_autpers = STR_B20,
    h22_autpers = STR_C20,
    h8j1_autpers = STR_D20,
    h8_inf_noperm = STR_A21,
    h18_inf_noperm = STR_B21,
    h22_inf_noperm = STR_C21,
    h8j1_inf_noperm = STR_D21,
    h8_autpers_nomed_noperm = STR_A22,
    h18_autpers_nomed_noperm = STR_B22,
    h22_autpers_nomed_noperm = STR_C22,
    h8j1_autpers_nomed_noperm = STR_D22,
    h8_smur = STR_A23,
    h18_smur = STR_B23,
    h22_smur = STR_C23,
    h8j1_smur = STR_D23,
    pass_24 = STR_A24,
    smur_24 = STR_A25,
    smur_totduree = STR_A26,
    autmed_plan = STR_A27,
    autpers_acc = STR_D59_AUTRE,
    ferm = STR_116_FERM,
    regul = STR_117_REGUL,
    absent = STR_55_ABSENT,
    rep_point = REP_POINTAGES,
    code_comm = CODE_COMMUNE,
    nom_comm = LIBELLE_COMMUNE,
    code_dep = DEP,
    nom_dep = LIBELLE_DEPARTEMENT,
    code_ancreg = ANCIENNE_REGION,
    nom_ancreg = LIBELLE_ANCIENNE_REGION,
    code_reg = NOUVELLE_REGION,
    nom_reg = LIBELLE_NOUVELLE_REGION,
    dens_med = DENSITE_MEDECINS_ENSEMBLE,
    dens_med_lib = DENSITE_MEDECINS_LIB,
    dens_gen = DENSITE_GENERALISTES_ENSEMBLE,
    dens_gen_lib = DENSITE_GENERALISTES_LIB,
    dens_spec = DENSITE_SPECIALISTES_ENSEMBLE,
    dens_spec_lib = DENSITE_SPECIALISTES_LIB,
    dens_ped = DENSITE_PEDIATRES_ENSEMBLE,
    dens_ped_lib = DENSITE_PEDIATRES_LIB,
    pass_4tr = NB_PASSAGES_4CL,
    categ_etab = CATEG,
    stat_jur = STATUT
  )